server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/heredoggy
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # SQL ??? ??

  # ??/?? ??? ??? ??
  jackson:
    time-zone: Asia/Seoul